services:
  nicotine:
    image: paulbismuth0/nicotine-plus
    ports:
      - 5800:5800
      - 5900:5900
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./nicotine
        target: /config/xdg/data/nicotine
