services:
  nicotine:
    image: paulbismuth0/nicotine-plus
    ports:
      - 6080:6080
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /config/xdg/data/nicotine
